# Generated by Django 2.2.14 on 2023-05-14 13:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
