# Generated by Django 2.2.14 on 2023-05-15 04:17

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230514_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=django_cryptography.fields.encrypt(models.FloatField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=django_cryptography.fields.encrypt(models.FloatField()),
        ),
    ]
